-- Inserir 5 vagas de emprego de exemplo
INSERT INTO job_vacancies (
  title, 
  company, 
  description, 
  location, 
  job_type, 
  salary_range,
  vacancies_count,
  workload,
  requirements,
  benefits,
  status,
  expires_at
) VALUES 
(
  'Auxiliar Administrativo',
  'Prefeitura de Afogados da Ingazeira',
  'Responsável por auxiliar nas atividades administrativas, atendimento ao público, organização de documentos e suporte às equipes.',
  'Afogados da Ingazeira - PE',
  'CLT',
  'R$ 1.500,00 - R$ 2.000,00',
  3,
  'Segunda a Sexta, 8h às 17h',
  'Ensino médio completo, conhecimentos em informática básica, boa comunicação',
  'Vale transporte, Vale alimentação',
  'active',
  NOW() + INTERVAL '30 days'
),
(
  'Assistente Social',
  'Secretaria de Assistência Social',
  'Atuar no acompanhamento de famílias em situação de vulnerabilidade social, elaboração de relatórios e visitas domiciliares.',
  'Afogados da Ingazeira - PE',
  'CLT',
  'R$ 2.800,00 - R$ 3.500,00',
  2,
  'Segunda a Sexta, 8h às 14h',
  'Graduação em Serviço Social, registro no CRESS ativo, experiência na área',
  'Vale transporte, Vale alimentação, Plano de saúde',
  'active',
  NOW() + INTERVAL '45 days'
),
(
  'Motorista CNH D',
  'Secretaria de Educação',
  'Conduzir veículos de transporte escolar, zelar pela segurança dos estudantes e realizar manutenção preventiva dos veículos.',
  'Afogados da Ingazeira - PE',
  'CLT',
  'R$ 2.200,00',
  5,
  'Segunda a Sexta, 6h às 14h',
  'CNH categoria D válida, experiência com transporte escolar, curso de transporte escolar',
  'Vale transporte, Vale alimentação',
  'active',
  NOW() + INTERVAL '20 days'
),
(
  'Professor de Educação Infantil',
  'Secretaria de Educação',
  'Ministrar aulas para crianças de 3 a 5 anos, desenvolver atividades pedagógicas e acompanhar o desenvolvimento dos alunos.',
  'Afogados da Ingazeira - PE',
  'Contrato Temporário',
  'R$ 2.500,00',
  4,
  'Segunda a Sexta, 7h às 13h',
  'Graduação em Pedagogia ou Normal Superior, experiência com educação infantil',
  'Vale transporte, Vale alimentação, Férias remuneradas',
  'active',
  NOW() + INTERVAL '15 days'
),
(
  'Técnico em Enfermagem',
  'Secretaria de Saúde',
  'Prestar assistência de enfermagem aos pacientes, auxiliar em procedimentos médicos e manter organização do posto de saúde.',
  'Afogados da Ingazeira - PE',
  'CLT',
  'R$ 2.000,00 - R$ 2.500,00',
  6,
  'Escala 12x36',
  'Curso técnico de enfermagem completo, registro no COREN ativo, experiência em unidade básica de saúde',
  'Vale transporte, Vale alimentação, Adicional noturno',
  'active',
  NOW() + INTERVAL '60 days'
);