// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqhjbelcouanvcrqudbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxaGpiZWxjb3VhbnZjcnF1ZGJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExODA0MTIsImV4cCI6MjA3Njc1NjQxMn0.hTcp_XDyNBmd5cX48Vh14D750bwVRWHuORzhK3lONHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});